services:
  db:
    image: mysql:8.0
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s


  redis:
    image: redis:alpine


  clamav:
    image: clamav/clamav:latest
    healthcheck:
      test: ["CMD", "clamdscan", "--version"]
      interval: 20s


  web:
    build: ./web
    env_file: .env
    volumes:
      - ./storage:/app/shared_uploads
    depends_on:
      db: { condition: service_healthy }
      clamav: { condition: service_healthy }


  proxy:
    image: nginx:latest
    ports: ["8081:8081"]
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [web]


volumes:
  db_data:
